name: Build and Release Chrome Extension

on:
  push:
    tags:
      - "v*" # Dispara a action quando um novo tag versionado (ex: v1.0.0) for criado
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: extension/package-lock.json

      - name: Instalar dependências
        working-directory: extension
        run: npm install

      - name: Construir extensão
        working-directory: extension
        run: npm run build

      - name: Compactar a pasta dist
        run: |
          cd extension
          zip -r ../chrome-extension.zip dist

      - name: Criar release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: chrome-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chrome extension to Chrome Web Store
        # You may pin to the exact commit or the version.
        # uses: MobileFirstLLC/cws-publish@569e87bc9a54ad7712ba6dc154a110d88af63b85
        uses: MobileFirstLLC/cws-publish@2.1.1
        with:
          # Desired action, one of: upload, publish, testers
          action: upload
          # Webstore API client id parameter
          client_id: ${{secrets.CHROME_CLIENT_ID}}
          # Webstore API client secret parameter
          client_secret: ${{secrets.CLIENT_SECRET}}
          # Webstore API refresh token
          refresh_token: ${{secrets.REFRESH_TOKEN}}
          # Path to extension .zip file
          zip_file: chrome-extension.zip
          # Unique identifier of the Chrome extension
          extension_id: ${{secrets.EXTENSION_ID}}
          
